### ISSUE TITLE
link from https://ts-info.readthedocs.io/en/latest/ not working

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/translationStudio-Info#1]
Hello,
The link for the 'edit on GitHub' on the readthedocs page is not working.

How can we edit the link so that it works?

**Comment by jag3773** [comment]
Which page?  I spot checked several including the main page and it takes me to the correct Github page for editing.

**Comment by ChrisJarka** [comment]
Wow - so yesterday it wasn't working and now today it is. Humph!
Thanks!
